Feature : 비밀번호 재설정 기능 추가
Kernel360/F1-WashPedia-BE pull request #178
Opened 2024-02-21 11:12 UTC by cgk95

## 💡 Motivation and Context
`비밀번호를 분실한 회원이 비밀번호를 재설정 할 수 있는 기능을 추가합니다.`

<br>

## 🔨 Modified
> 비밀번호를 분실한 경우, 회원 아이디를 통해 비밀번호를 재설정할 수 있도록 합니다.
  - _`회원 아이디`로 `비밀번호 찾기 요청`을 합니다._
  - _아이디를 통해 회원가입시 입력한 이메일를 조회합니다_
  - _해당 이메일로 비밀번호 재설정이 가능한 `URL 링크`를 발송합니다_
      - _링크에는 5분간 유효한 `UUID` 토큰이 포함되어 있습니다._
      -  _토큰은 `Redis`에 저장되어 `유효시간이 지나면 자동으로 사라집니다`._
  - 이메일에서 URL 링크를 클릭하면 먼저 서버에 요청을 보냅니다
      - 서버에서는 요청의 쿼리 파라미터로 포함된 `UUID` 토큰이 유효한지 판단합니다.
      - 유효하다면  비밀번호 재설정이 가능한 화면으로 이동합니다.
  - 재설정 화면에서 변경할 비밀번호와 토큰을 전달합니다.
      - 토큰 유효성을 다시 확인하고 비밀번호를 재설정합니다.
      - 이후 사용된 토큰을 폐기합니다.
      - 
![image](https://github.com/Kernel360/F1-WashPedia-BE/assets/73059667/ae5fdd82-4369-4e8e-8f88-bbc9db493024)

> 이메일을 발송하는 서비스와, 실제 아이디/비밀번호 찾기를 수행하는 서비스를 분리하였습니다.

> 아이디/비밀번호 찾기에 사용되는 DTO 클래스를 `MemberCredentialDto.java` 로 통합하였습니다.

<br>

## 🌟 More
- _Redis 관련 클래스들을 현재 api 모듈에 두었는데(api 모듈에서 인증관련으로만 사용하니까), domain 모듈에 두어야 하는지 고민하고 있습니다. _

<br>

---

### 📋 커밋 전 체크리스트
- [x] 추가/변경에 대한 단위 테스트를 완료하였습니다.
- [x] 컨벤션에 맞게 작성하였습니다.

<br>

### 🤟🏻 PR로 완료된 이슈
closes #158

2024-02-22 01:39 UTC, linglong67 requested changes
내용 전체적으로 한번 봤는데요~ 
대부분 LGTM이지만 수정이 필요한 부분들이 있어 보여서 확인 부탁드릴게요!

(그리고 프론트 연계 테스트까지 완료되면 서버 배포하실 거라고 하셨죠!? 그때는 같이 작업해야 하니까 말씀해주세요ㅎㅎ)

2024-02-22 01:39 UTC, linglong67 commented on module-api/src/test/java/com/kernel360/member/controller/MemberControllerTest.java
테스트코드 빠르게 적응하셨군요ㅎㅎ 굿입니다 👍

2024-02-22 01:45 UTC, cgk95 commented on module-api/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
starter-data-redis 이 기본 레디스이고, reactive redis 라고 리액티브 방식을 지원하는 레디스도 있더라구요

2024-02-22 01:45 UTC, cgk95 commented on module-api/src/main/java/com/kernel360/member/controller/MemberController.java
> +
제거하도록 하겠습니다

2024-02-22 01:53 UTC, cgk95 commented on module-api/src/main/java/com/kernel360/member/dto/MemberCredentialDto.java
> +                                  @JsonProperty("password") String password) {
ObjectMapper 관련해서 직렬화/역직렬화 시 매핑이 안되는 문제가 있었는데, 문제 해결과정중에 해결책 중 하나로 시도했었습니다.

해당 문제는 오타 때문에 발생했었던 것을 확인했기 때문에 삭제하여도 문제가 없습니다. 

다만 `@JsonProperty` 어노테이션으로 명시해주면 json의 key 값과  백엔드 쪽 변수명이 달라도 동작할 수 있다는 소소한 이점이 있어서 지우지 않고 내버려두었습니다.

어노테이션을 삭제하는 편이 좋을 것 같다고 말씀하시면 삭제하도록하겠습니다.

2024-02-22 01:56 UTC, cgk95 commented on module-api/src/main/java/com/kernel360/member/service/FindCredentialService.java
> +                                               .scheme("http")
해당 문제 때문에 현재는 이 부분을 주석처리해 놓았습니다. 지정하지 않으면 기본 `https` 로 동작합니다.

`uriString` 을 만들 때, `HttpServeletRequest` 에서 요청의 호스트를 읽어서 지정하고 있는데, 호스트를 프로파일별로 .yml 에 상수로 지정하여 사용하도록 변경하면 더 유연하게 사용할 수 있습니다.

2024-02-22 01:58 UTC, cgk95 commented on module-api/src/main/resources/application-local.yml
> +      password:
도커 공식 redis 이미지에 기본설정이 패스워드가 지정되어 있지 않더라구요. 급해서 그냥 비밀번호 지정하는 과정을 스킵했습니다.

dev, prod 에는 비밀번호를 지정해서 사용해야 합니다

2024-02-22 02:00 UTC, cgk95 commented on module-api/src/main/java/com/kernel360/member/service/FindCredentialService.java
> +        return valueOperations.get(key); // TODO :: refactor
아 해놓고 주석을 안 지웠습니다. 처음에 이메일을 보내는 서비스와 토큰 유효성을 확인하는 서비스가 한 클래스에 있었는데 그것을 분리하는 작업을 해야한다는 것을 기억하기 위해서 남겼던 주석입니다.

삭제하도록 하겠습니다.

2024-02-22 02:53 UTC, linglong67 reviewed
답변 주신 부분들 확인했습니다~!
이후 추가작업 하신 부분 확인되면 승인 처리할게요ㅎㅎ

2024-02-22 02:53 UTC, linglong67 commented on module-api/src/main/java/com/kernel360/member/dto/MemberCredentialDto.java
> +                                  @JsonProperty("password") String password) {
현재는 변수명이 같아서 굳이 없어도 될 것 같긴 하지만, 이건 선택(?)하시기 나름인 것 같아 일단 찬규님이 원하시는 대로 하셔도..ㅎㅎ

2024-02-22 05:10 UTC, HyunJunSon approved these changes
LGTM

2024-02-22 05:10 UTC, HyunJunSon commented on module-api/src/main/java/com/kernel360/member/service/FindCredentialService.java
> +                                               .scheme("http")
관리하는 면에서는 html 파일 따로 만들고, 템플릿엔진으로 하는게 더 좋을거 같긴한데, 문자열로 넣으신 다른 이유가 있나요?( 순수 호기심..)

2024-02-22 06:25 UTC, cgk95 commented on module-api/src/main/java/com/kernel360/member/service/FindCredentialService.java
> +                                               .scheme("http")
@HyunJunSon 급해서 그냥 문자열로 가져다 넣었습니다.. 말씀하신대로 html 파일로 관리하도록 변경해야 합니다.

2024-02-22 06:38 UTC, cgk95 commented on module-api/src/main/java/com/kernel360/member/controller/MemberController.java
> +        String memberId = findCredentialService.getData(token);
재설정 하이퍼 링크를 서버에서 이메일로 전달하는 방식이라 일반적인 토큰 통신 처럼 헤더에 값을 포함하는 것은 어려울 것 같습니다.
다만 링크 전달 이후의 통신에는 적용할 수 있을 것 같으니 염두에 두고 있겠습니다.

<img width="1249" alt="image" src="https://github.com/Kernel360/F1-WashPedia-BE/assets/73059667/eb96c1c4-6170-4b24-b8b4-8a2d87c70742">

2024-02-22 10:06 UTC, gunsight1 approved these changes

2024-02-22 10:06 UTC, gunsight1 commented on module-api/src/main/java/com/kernel360/global/config/RedisConfig.java
> +        redisTemplate.setConnectionFactory(redisConnectionFactory());
여기서 실제 연결을 하겠네요 (아마도?)

2024-02-22 10:06 UTC, gunsight1 commented on module-api/src/main/java/com/kernel360/member/service/FindCredentialService.java
> +    public void sendPasswordResetUri(String resetUri, MemberDto dto) {
지금같은 스타일로도 구현이 가능한데 추후에 html같은 별도 퍼블파일을 받게되면 파일을 읽어서 뿌리는 방법으로 라인수가 깔끔해질수있습니다.

2024-02-22 10:06 UTC, gunsight1 commented on module-api/src/main/java/com/kernel360/member/service/FindCredentialService.java
> +        if (value == null) {
value == null체크는 Objects.isNull로도 체크가 가능합니다. 이거는 윤진멘토님 코맨트에 붙어있던 내용이고...
String 타입은 실제 있는지 없는지 판단이 중요할 땐 length로 비교하는게 더 정확하다고 생각합니다. 이전 제가 올린 PR에 시행착오 내용이 있습니다.

2024-02-22 10:06 UTC, gunsight1 commented on module-api/src/test/java/com/kernel360/member/controller/MemberControllerTest.java
> +                       "member/find-memberId", getDocumentRequest(), getDocumentResponse(),
request response 안빼먹고 잘 넣으셧네요

2024-02-22 10:33 UTC, cgk95 commented on module-api/src/main/java/com/kernel360/member/service/FindCredentialService.java
> +        if (value == null) {
Objects.isNull() 로 체크하는 방식으로 변경하겠습니다. 
또한 위 코드는 key 와 매칭이 되는 값이 없으면 null 을 반환합니다. 따라서 .length()==0 만으로는 검증이 어려울 것 같습니다.
관련해서는 조금 더 생각해보겠습니다.

2024-02-22 10:39 UTC, linglong67 approved these changes
확인했습니다~!

2024-02-22 10:40 UTC, merged

2024-02-25 07:36 UTC, cgk95 commented on module-api/src/main/java/com/kernel360/member/service/FindCredentialService.java
> +        if (value == null) {
[링크](https://creampuffy.tistory.com/120)

StringUtils.hasLength() 를 사용해야 함을 이해했습니다.