Feature/product testcode
Kernel360/F1-WashPedia-BE pull request #57
Opened 2024-01-15 07:24 UTC by HyunJunSon

## 💡 Motivation and Context
- product testCode 작성
- fixture Monkey library 적용
- Id 값 Integer -> Long 타입 변경
- 배치코드 추가에 따른 도커컴포즈 이미지 추가

<br>

## 🔨 Modified
> 여기에 무엇이 크게 바뀌었는지 설명해 주세요
  - _여기에 세부 변경사항을 설명해주세요_

<br>

## 🌟 More
- _여기에 PR 이후 추가로 해야 할 일에 대해서 설명해 주세요_

- 마이페이지, 메인페이지 도메인 코드, 테스트코드 작성
<br>

---

### 📋 커밋 전 체크리스트
- [ㅇ] 추가/변경에 대한 단위 테스트를 완료하였습니다.
- [ㅇ] 컨벤션에 맞게 작성하였습니다.

<br>

### 🤟🏻 PR로 완료된 이슈
closes #

2024-01-16 01:53 UTC, linglong67 approved these changes
요약 및 덧붙이자면,

1) PR은 제목과 내용이 매치가 잘 되면 좋을 것 같음
2) fixture monkey 테스트 코드는 LGTM!
3) entity, dto 내 Integer → Long 으로 변경된 부분들은 flyway로 컬럼 정보 업데이트 필요

입니다..!
(근데요.. 커밋 이력은 살짝 꼬인건가요..? ㅋㅋㅋ)

2024-01-16 01:53 UTC, linglong67 commented on docker-compose.yml
이후에는 PR을 구분해서 올려주시는 게 좋을 것 같아요!
PR 명과 내부 작업 사항이 다른 부분들이 있어서 나중에 이력 관리가 어려울 수도 있지 않을까요!?

2024-01-16 01:53 UTC, linglong67 commented on module-api/lombok.config
내용에 대해 간략하게 설명해주시면 좋을 것 같아요~
(이 설정이 필요하게 된 이유랄까요??)

2024-01-16 01:53 UTC, linglong67 commented on module-api/src/main/java/com/kernel360/member/dto/MemberDto.java
>          );
이거 이대로면 memberDto.toEntity(memberDto) 같은 형태로 호출되게 될 것 같은데요
memberDto.toEntity() 형태가 더 나아보여요! (매개변수가 의미가 있을까 싶어서요)

2024-01-16 01:53 UTC, linglong67 commented on module-api/src/test/java/com/kernel360/product/dto/ProductDtoTest.java
fixture monkey 사용 예시가 생겨서 좋네요 👍
다음에 한번 간략하게 설명 듣고 싶어요!

2024-01-16 02:09 UTC, cgk95 requested changes
잘 읽었습니다.
엔티티의 Id 타입을 Long으로 변경한 것 확인했어요. SERIAL 타입이 Integer와 Long을 모두 쓸 수 있는 거군요. 그런데 결국 정수범위 때문에 BIGSERIAL 로 바꿔야 하는 거 아닌가 싶습니다. flyway 스크립트로 타입 변경을 해야 할 거 같아요.

![image](https://github.com/Kernel360/F1-WashPedia-BE/assets/73059667/118da216-ab1b-4fb3-bfc9-e922ff1700c3)

2024-01-16 02:51 UTC, cgk95 approved these changes
LGTM. 질문 남겼습니다

2024-01-16 02:51 UTC, cgk95 commented on module-api/src/test/java/com/kernel360/product/controller/ProductControllerTest.java
> +                .objectIntrospector(new FailoverIntrospector(
objectIntrospector 와 FailoverIntrospector 가 어떤 역할을 하나요?

2024-01-16 02:51 UTC, cgk95 commented on module-api/src/test/java/com/kernel360/product/controller/ProductControllerTest.java
> +                                BuilderArbitraryIntrospector.INSTANCE
각각의 Introspector 가 어떤 역할을 하는지 알려주실 수 있나요

2024-01-17 02:12 UTC, gunsight1 commented on module-api/src/main/java/com/kernel360/member/dto/MemberDto.java
>          );
확인해봤는데 this로 보내나 memberDto로 보내나 둘다 toEntity(memberDto)로 해줘야됩니다.
회원 가입, 로그인 구현하는 동안은 member정보를 통으로 바인딩 할 일이 없어서 toEntity를 쓰지 않았는데
이런 고민이 있겠구나 하는걸 이제야 알았네요

2024-01-17 02:17 UTC, gunsight1 commented on module-api/src/test/java/com/kernel360/product/controller/ProductControllerTest.java
> +                .objectIntrospector(new FailoverIntrospector(
네이밍 추측만 보면 전자는 객체생성준비자같고 후자는 실패값이 떨어질때까지 만들어주는 생성자? 같은거 같네요

2024-01-17 02:19 UTC, gunsight1 approved these changes
고생하셨습니다 추후 PR에 flyway 파일 하나 추가하여서 테이블 컬럼들의 대한 serial4 -> serial8까지 추가해주시면 감사하겠습니다

2024-01-17 02:20 UTC, merged